name: Correr Scraper Diario

on:
  schedule:
    - cron: '0 9 * * *' # Corre todos los días a las 09:00 AM UTC
  workflow_dispatch: # Esto permite que lo corras manualmente cuando quieras desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANTE: Esto permite que el robot guarde el archivo
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Correr el scraper
        run: python scraper.py

      - name: Guardar cambios en el repo
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add datos.json
          git commit -m "Actualizando datos del scraper" || echo "No hay cambios para commitear"
          git push